openapi: 3.0.0
info:
  title: Sevand.ru
  description: "Public API"
  version: 1.0

servers:
  - url: http://sevand.local/api
    description: ""

################################################################################
paths:
  /student/get:
    get:
      summary: Get Student
      description: Returns the student by id
      tags:
        - Student
      parameters:
        - name: id
          in: query
          required: true
          description: Id student
          schema:
            type: string
        - name: lang
          in: query
          required: false
          description: Error Language (en/ru)
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

################################################################################
components:
  schemas:
    Student:
      properties:
        id:
          type: integer
          description: Id student
        name:
          type: string
          description: Name student
        surname:
          type: string
          description: Surname student
        patronymic:
          type: string
          description: Patronymic student
        status:
          type: string
          description: Status student
        user:
          properties:
            id:
              type: integer
              description: Id user
            username:
              type: string
              description: Username user
        group:
          properties:
            id:
              type: integer
              description: Id group
            title:
              type: string
              description: Group name
            course:
              type: string
              description: Course group
        department:
          properties:
            id:
              type: integer
              description: Id department
            name:
              type: string
              description: Department short name